USE [master]
GO

/****** Object:  Database [Rapid]    Script Date: 2/11/2022 12:13:57 a. m. ******/
CREATE DATABASE [Rapid]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Rapid', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Rapid.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Rapid_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Rapid_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Rapid].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Rapid] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Rapid] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Rapid] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Rapid] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Rapid] SET ARITHABORT OFF 
GO

ALTER DATABASE [Rapid] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Rapid] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Rapid] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Rapid] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Rapid] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Rapid] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Rapid] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Rapid] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Rapid] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Rapid] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Rapid] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Rapid] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Rapid] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Rapid] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Rapid] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Rapid] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Rapid] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Rapid] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Rapid] SET  MULTI_USER 
GO

ALTER DATABASE [Rapid] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Rapid] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Rapid] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Rapid] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Rapid] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Rapid] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Rapid] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Rapid] SET  READ_WRITE 
GO


